[package]
name = "backbeat_vf_fuse"
version = "0.1.0"
edition.workspace = true
authors = ["zkldi <zkldi@proton.me>"]
readme = "README.md"
license = "GPL-3.0"
repository = "https://github.com/zkldi/backbeat"

[dependencies]
backbeat_vf_fs = { workspace = true }
backbeat_sdk = { workspace = true }
fuser = { workspace = true }
nix = { workspace = true, features = ["user"] }
parking_lot = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
backbeat_sdk = { workspace = true, features = ["test-util"] }
backbeat_packager = { workspace = true }
walkdir = { workspace = true }
