[package]
name = "backbeat_vf_app"
version = "0.1.0"
edition.workspace = true
authors = ["zkldi <zkldi@proton.me>"]
readme = "README.md"
license = "GPL-3.0"
repository = "https://github.com/zkldi/backbeat"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "backbeat-vf"
path = "src/main.rs"

[build-dependencies]
tauri-build.workspace = true
vergen-git2.workspace = true

[dependencies]
backbeat_vf_config.workspace = true
backbeat_vf_mountd.workspace = true
directories.workspace = true
open.workspace = true
serde.workspace = true
tauri.workspace = true
tauri-plugin-dialog.workspace = true
tokio.workspace = true
