[package]
name = "rg_formats"
version = "0.2.0"
edition.workspace = true
description = "Parsers and Serializers for various rhythm game formats."
license = "MIT"
readme = "README.md"
authors = ["zkldi <zkldi@proton.me>"]
repository = "https://github.com/zkldi/backbeat"

[features]
default = ["serde"]
serde = ["dep:serde"]

[dependencies]
encoding_rs.workspace = true
lexical.workspace = true
regex.workspace = true
thiserror.workspace = true
tracing.workspace = true
serde = { workspace = true, features = ["derive"], optional = true }
serde_json = { workspace = true }
derive_more = { workspace = true, features = ["from"] }

[dev-dependencies]
criterion = { workspace = true, features = ["html_reports"] }
pretty_assertions.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[[bench]]
name = "parse_formats"
harness = false
