package ac.backbeat.sdk;

import com.sun.jna.IntegerType;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.Union;
import com.sun.jna.ptr.ByReference;
import com.sun.jna.ptr.ByteByReference;
import com.sun.jna.ptr.IntByReference;
import com.sun.jna.ptr.LongByReference;
import com.sun.jna.ptr.PointerByReference;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.Locale;
import java.util.Map;

/**
 * Autogenerated bindings to the backbeat_sdk.
 *
 * I don't understand this code, so don't ask me about it.
 */
interface NativeBindings extends Library {
    int OK = 0;
    int ERR_DB = 1;
    int ERR_CORRUPT = 2;
    int ERR_MIGRATE = 3;
    int ERR_IO = 4;
    int ERR_CONFIG = 5;
    int ERR_JSON = 6;
    int ERR_INVALID_COLLECTION_HEADER = 7;
    int ERR_INVALID_BUNDLE = 8;
    int ERR_TOO_LARGE = 9;
    int ERR_ZIP = 10;
    int ERR_NESTED_BBZIP = 11;
    int ERR_PARSE = 12;
    int LIBVERSION = 1;
    int NOT_FOUND = 13;
    int ERR_HASH_MISMATCH = 14;
    int ERR_INVALID_PRECOMBINED_ASSETS = 15;
    int ERR_INVALID_ASSET_PATH = 16;
    int ERR_ID_MISMATCH = 17;
    int ERR_NO_SERVERS = 18;
    int ERR_INVALID_URL = 19;
    int ERR_NETWORK = 20;
    int ERR_UNKNOWN_ALGORITHM = 21;
    int ERR_PERMISSION_DENIED = 22;
    int ERR_CANCELLED = 23;
    int ERR_REMOTE_BAD_STATUS_CODE = 24;
    int ERR_DOWNLOAD_TASK_FAILED = 25;
    int ERR_NULL_ARG = 1000;
    int ERR_PANIC = 1001;
    int ERR_INVALID_STRING = 1002;
    int ERR_INCOMPATIBLE_SQLITE = 1004;
    int ASSET_DATA_BYTES = 1;
    int ASSET_DATA_FILE = 2;
    int DATA_CHART = 1;
    int DATA_BUNDLE = 2;
    int DATA_ASSET = 3;
    int COLLECTION_TABLE = 1;
    int COLLECTION_COURSE = 2;
    int COLLECTION_PACK = 3;
    int DOWNLOAD_QUEUED = 0;
    int DOWNLOAD_DOWNLOADING = 1;
    int DOWNLOAD_VERIFYING = 2;
    int DOWNLOAD_COMMITTING = 3;
    int DOWNLOAD_DONE = 4;
    int DOWNLOAD_FAILED = 5;
    int DOWNLOAD_CANCELLED = 6;

    NativeBindings INSTANCE = Loader.load();

    int bkb_libversion();
    Pointer bkb_libcommithash();
    int bkb_sqlite_version_number();
    Pointer bkb_error_string(int code);

    int bkb_bb_from_file(String path, PointerByReference outBundle);
    int bkb_bb_from_json(byte[] json, SizeT jsonLen, PointerByReference outBundle);
    void bkb_bb_free(Pointer bundle);
    int bkb_bb_to_json(Pointer bundle, BkbBytes outJson);
    int bkb_bb_chart_sha256(Pointer bundle, BkbString outSha256);
    int bkb_bb_bundle_id(Pointer bundle, BkbString outBundleId);
    int bkb_bb_combined_assets_id(Pointer bundle, BkbString outCombinedAssetsId);
    int bkb_bb_resolve_path(Pointer bundle, String path, BkbString outAssetId);

    int bkb_store_open(PointerByReference outStore);
    void bkb_store_free(Pointer store);
    int bkb_store_config_dir(Pointer store, BkbString out);
    int bkb_store_dir(Pointer store, BkbString out);
    int bkb_store_logs_dir(Pointer store, BkbString out);
    int bkb_store_sqlite_connection_url(Pointer store, BkbString out);
    int bkb_store_sqlite_attach_command(Pointer store, BkbString out);
    int bkb_store_sqlite_detach_command(Pointer store, BkbString out);
    int bkb_store_stats(Pointer store, BkbStats outStats);
    int bkb_store_should_refresh(Pointer store, long lastRevision, ByteByReference outShouldRefresh, LongByReference outRevision);

    int bkb_store_get_asset(Pointer store, String assetId, BkbAssetData outData);
    int bkb_store_resolve_path(Pointer store, String bundleId, String assetPath, BkbAssetData outData);
    int bkb_store_get_bundle(Pointer store, String bundleId, PointerByReference outBundle);
    int bkb_store_get_chart(Pointer store, String chartId, PointerByReference outBundle);
    int bkb_store_get_chart_data(Pointer store, String chartId, BkbBytes outData);
    int bkb_store_get_course(Pointer store, String url, PointerByReference outCourse);
    int bkb_store_get_pack(Pointer store, String url, PointerByReference outPack);
    int bkb_store_get_table(Pointer store, String url, PointerByReference outTable);
    int bkb_table_chart_count(Pointer table, SizeTByReference outCount);

    int bkb_store_has_asset(Pointer store, String assetId, ByteByReference out);
    int bkb_store_has_bundle(Pointer store, String bundleId, ByteByReference out);
    int bkb_store_has_chart(Pointer store, String chartId, ByteByReference out);
    int bkb_store_has_collection(Pointer store, String url, ByteByReference out);
    int bkb_store_has_course(Pointer store, String url, ByteByReference out);
    int bkb_store_has_pack(Pointer store, String url, ByteByReference out);
    int bkb_store_has_table(Pointer store, String url, ByteByReference out);
    int bkb_store_has_zero_data_servers(Pointer store, ByteByReference out);

    int bkb_store_import_asset(Pointer store, String path);
    int bkb_store_import_bbzip(Pointer store, String path);
    int bkb_store_import_bundle(Pointer store, Pointer bundle, BkbString outBundleId);
    int bkb_store_export_chart(Pointer store, String chartId, String output, byte bbzip);
    int bkb_store_export_bundle(Pointer store, String bundleId, String output, byte bbzip);
    int bkb_store_search_bundles(Pointer store, String query, long offset, int limit,
                                 String[] extensions, SizeT extensionsLen, PointerByReference outResult);
    int bkb_store_list_tables(Pointer store, String[] gamemodes, SizeT gamemodesLen, PointerByReference outList);
    int bkb_store_list_courses(Pointer store, String[] gamemodes, SizeT gamemodesLen, PointerByReference outList);
    int bkb_store_list_packs(Pointer store, String[] gamemodes, SizeT gamemodesLen, PointerByReference outList);

    int bkb_store_server_add(Pointer store, BkbServerConfig server);
    int bkb_store_server_rm(Pointer store, BkbServerConfig server);
    int bkb_store_server_download_asset(Pointer store, String assetId);
    int bkb_store_server_download_bundle(Pointer store, String bundleId);
    int bkb_store_server_download_chart(Pointer store, String chartId);
    int bkb_store_bundle_download_assets(Pointer store, String bundleId);
    int bkb_store_bundle_rm(Pointer store, String bundleId);

    int bkb_store_download_progress(Pointer store, BkbDataId dataId, BkbOptionalDownloadProgress outProgress);
    int bkb_store_download_all_progress(Pointer store, BkbDownloadSnapshotList outProgress);
    int bkb_store_download_overview(Pointer store, BkbDownloadOverview outOverview);
    int bkb_store_download_list(Pointer store, long offset, int limit, BkbDownloadListResult outResult);
    int bkb_store_collection_download_list(Pointer store, long offset, int limit, BkbDownloadListResult outResult);
    int bkb_store_download_cancel(Pointer store, BkbDataId dataId, ByteByReference outCancelled);
    int bkb_store_download_asset_cancel(Pointer store, String assetId, ByteByReference outCancelled);
    int bkb_store_download_bundle_cancel(Pointer store, String bundleId, ByteByReference outCancelled);
    int bkb_store_download_chart_cancel(Pointer store, String chartId, ByteByReference outCancelled);
    int bkb_store_download_clear_finished(Pointer store, SizeTByReference outCount);

    int bkb_store_collection_fetch_download_data(Pointer store, String url, BkbCollectionDownloadDataReport outReport);
    int bkb_store_collection_fetch_header(Pointer store, String url, BkbCollectionHeader outHeader);
    int bkb_store_collection_fetch_upsert(Pointer store, String url, BkbCollectionUpsertResult outResult);
    int bkb_store_collection_rm(Pointer store, String url, byte removeChartsToo, IntByReference outKind);
    int bkb_store_corruption_check(Pointer store, PointerByReference outReport);
    int bkb_store_corruption_repair(Pointer store);
    int bkb_store_asset_prune(Pointer store, byte dryRun, LongByReference outCount);
    int bkb_store_disk_prune(Pointer store, byte dryRun, LongByReference outCount);

    void bkb_string_free(BkbString.ByValue value);
    void bkb_bytes_free(BkbBytes.ByValue value);
    void bkb_asset_data_free(BkbAssetData.ByValue value);
    void bkb_bundle_search_result_free(Pointer result);
    void bkb_corruption_report_free(Pointer report);
    void bkb_collection_metadata_list_free(Pointer list);
    void bkb_collection_download_data_report_free(BkbCollectionDownloadDataReport.ByValue report);
    void bkb_download_snapshot_list_free(BkbDownloadSnapshotList.ByValue list);
    void bkb_download_overview_free(BkbDownloadOverview.ByValue overview);
    void bkb_download_list_result_free(BkbDownloadListResult.ByValue result);
    void bkb_course_free(Pointer course);
    void bkb_pack_free(Pointer pack);
    void bkb_table_free(Pointer table);

    final class SizeT extends IntegerType {
        public SizeT() { this(0); }
        public SizeT(long value) { super(Native.SIZE_T_SIZE, value, true); }
    }

    final class SizeTByReference extends ByReference {
        public SizeTByReference() { super(Native.SIZE_T_SIZE); }
        public SizeT getValue() {
            return new SizeT(Native.SIZE_T_SIZE == 8 ? getPointer().getLong(0) : Integer.toUnsignedLong(getPointer().getInt(0)));
        }
    }

    @Structure.FieldOrder({"ptr", "len"})
    class BkbString extends Structure {
        public Pointer ptr;
        public SizeT len;
        ByValue byValue() { ByValue value = new ByValue(); value.ptr = ptr; value.len = len; value.write(); return value; }
        public static final class ByValue extends BkbString implements Structure.ByValue {}
    }

    @Structure.FieldOrder({"ptr", "len"})
    class BkbBytes extends Structure {
        public Pointer ptr;
        public SizeT len;
        ByValue byValue() { ByValue value = new ByValue(); value.ptr = ptr; value.len = len; value.write(); return value; }
        public static final class ByValue extends BkbBytes implements Structure.ByValue {}
    }

    @Structure.FieldOrder({"ptr", "len"})
    class BkbStr extends Structure {
        public Pointer ptr;
        public SizeT len;
        public BkbStr() {}
        public BkbStr(Pointer pointer) { super(pointer); read(); }
    }

    @Structure.FieldOrder({"filename", "assets", "assetsLen", "desc", "chart", "chartLen"})
    class BkbBb extends Structure {
        public BkbStr filename;
        public Pointer assets;
        public SizeT assetsLen;
        public BkbStr desc;
        public Pointer chart;
        public SizeT chartLen;
        BkbBb() {}
        BkbBb(Pointer pointer) { super(pointer); read(); }
    }

    @Structure.FieldOrder({"bundleId", "description", "extension"})
    class BkbBundleSearchChart extends Structure {
        public BkbStr bundleId;
        public BkbStr description;
        public BkbStr extension;
        public BkbBundleSearchChart() {}
        public BkbBundleSearchChart(Pointer pointer) { super(pointer); read(); }
    }

    @Structure.FieldOrder({"charts", "chartsLen", "hasMore", "total"})
    class BkbBundleSearchResult extends Structure {
        public Pointer charts;
        public SizeT chartsLen;
        public byte hasMore;
        public long total;
        BkbBundleSearchResult() {}
        BkbBundleSearchResult(Pointer pointer) { super(pointer); read(); }
    }

    class BkbAssetDataValue extends Union { public BkbBytes bytes; public BkbString file; }

    @Structure.FieldOrder({"kind", "value"})
    class BkbAssetData extends Structure {
        public int kind;
        public BkbAssetDataValue value;
        @Override public void read() { super.read(); value.setType(kind == ASSET_DATA_BYTES ? BkbBytes.class : BkbString.class); value.read(); }
        ByValue byValue() { ByValue result = new ByValue(); result.kind = kind; result.value = value; result.write(); return result; }
        public static final class ByValue extends BkbAssetData implements Structure.ByValue {}
    }

    @Structure.FieldOrder({"seconds", "nanoseconds"})
    class BkbTimestamp extends Structure { public long seconds; public int nanoseconds; }

    @Structure.FieldOrder({"url", "name", "gamemode", "updated", "installed", "outOf"})
    class BkbCollectionMetadata extends Structure {
        public BkbStr url; public BkbStr name; public BkbStr gamemode; public BkbTimestamp updated; public long installed; public long outOf;
        public BkbCollectionMetadata() {}
        public BkbCollectionMetadata(Pointer pointer) { super(pointer); read(); }
    }

    @Structure.FieldOrder({"items", "itemsLen"})
    class BkbCollectionMetadataList extends Structure {
        public Pointer items; public SizeT itemsLen;
        BkbCollectionMetadataList(Pointer pointer) { super(pointer); read(); }
    }

    @Structure.FieldOrder({"lastModified", "kind"})
    class BkbCollectionHeader extends Structure {
        public BkbTimestamp lastModified; public int kind;
        public BkbCollectionHeader() {}
        public BkbCollectionHeader(Pointer pointer) { super(pointer); read(); }
    }

    @Structure.FieldOrder({"kind", "status"})
    class BkbCollectionUpsertResult extends Structure {
        public int kind; public int status;
        public BkbCollectionUpsertResult() {}
        public BkbCollectionUpsertResult(Pointer pointer) { super(pointer); read(); }
    }

    @Structure.FieldOrder({"chartSha256", "alg", "storedId", "computedId"})
    class BkbWrongChartId extends Structure {
        public BkbStr chartSha256; public BkbStr alg; public BkbStr storedId; public BkbStr computedId;
        public BkbWrongChartId() {}
        public BkbWrongChartId(Pointer pointer) { super(pointer); read(); }
    }

    @Structure.FieldOrder({"chartSha256", "alg", "reason"})
    class BkbUncomputedChartId extends Structure {
        public BkbStr chartSha256; public BkbStr alg; public BkbStr reason;
        public BkbUncomputedChartId() {}
        public BkbUncomputedChartId(Pointer pointer) { super(pointer); read(); }
    }

    @Structure.FieldOrder({"bundleId", "path", "assetId"})
    class BkbDanglingAssetRef extends Structure {
        public BkbStr bundleId; public BkbStr path; public BkbStr assetId;
        public BkbDanglingAssetRef() {}
        public BkbDanglingAssetRef(Pointer pointer) { super(pointer); read(); }
    }

    @Structure.FieldOrder({"largeAssetCount", "chartCount", "chartIdCount", "missingAssets", "missingAssetsLen",
            "corruptAssets", "corruptAssetsLen", "corruptCharts", "corruptChartsLen", "wrongChartIds", "wrongChartIdsLen",
            "uncomputableChartIds", "uncomputableChartIdsLen", "danglingAssetRefs", "danglingAssetRefsLen", "ok", "issueCount"})
    class BkbCorruptionReport extends Structure {
        public SizeT largeAssetCount; public SizeT chartCount; public SizeT chartIdCount;
        public Pointer missingAssets; public SizeT missingAssetsLen;
        public Pointer corruptAssets; public SizeT corruptAssetsLen;
        public Pointer corruptCharts; public SizeT corruptChartsLen;
        public Pointer wrongChartIds; public SizeT wrongChartIdsLen;
        public Pointer uncomputableChartIds; public SizeT uncomputableChartIdsLen;
        public Pointer danglingAssetRefs; public SizeT danglingAssetRefsLen;
        public byte ok; public SizeT issueCount;
        BkbCorruptionReport() {}
        BkbCorruptionReport(Pointer pointer) { super(pointer); read(); }
    }

    @Structure.FieldOrder({"key", "value"})
    class BkbTag extends Structure {
        public BkbStr key; public BkbStr value;
        public BkbTag() {}
        public BkbTag(Pointer pointer) { super(pointer); read(); }
    }

    @Structure.FieldOrder({"path", "id"})
    class BkbAsset extends Structure {
        public BkbStr path; public BkbStr id;
        public BkbAsset() {}
        public BkbAsset(Pointer pointer) { super(pointer); read(); }
    }

    @Structure.FieldOrder({"id", "desc", "tags", "tagsLen", "bundleId"})
    class BkbCourseChart extends Structure {
        public BkbStr id; public BkbStr desc; public Pointer tags; public SizeT tagsLen; public BkbStr bundleId;
        public BkbCourseChart() {}
        public BkbCourseChart(Pointer pointer) { super(pointer); read(); }
    }

    @Structure.FieldOrder({"name", "updated", "gamemode", "tags", "tagsLen", "assets", "assetsLen", "charts", "chartsLen"})
    class BkbCourse extends Structure {
        public BkbStr name; public BkbTimestamp updated; public BkbStr gamemode; public Pointer tags; public SizeT tagsLen;
        public Pointer assets; public SizeT assetsLen; public Pointer charts; public SizeT chartsLen;
        BkbCourse() {}
        BkbCourse(Pointer pointer) { super(pointer); read(); }
    }

    @Structure.FieldOrder({"id", "desc", "tags", "tagsLen", "installed"})
    class BkbPackBundle extends Structure {
        public BkbStr id; public BkbStr desc; public Pointer tags; public SizeT tagsLen; public byte installed;
        public BkbPackBundle() {}
        public BkbPackBundle(Pointer pointer) { super(pointer); read(); }
    }

    @Structure.FieldOrder({"name", "gamemode", "updated", "tags", "tagsLen", "assets", "assetsLen", "bundles", "bundlesLen"})
    class BkbPack extends Structure {
        public BkbStr name; public BkbStr gamemode; public BkbTimestamp updated; public Pointer tags; public SizeT tagsLen;
        public Pointer assets; public SizeT assetsLen; public Pointer bundles; public SizeT bundlesLen;
        BkbPack() {}
        BkbPack(Pointer pointer) { super(pointer); read(); }
    }

    @Structure.FieldOrder({"id", "desc", "tags", "tagsLen", "bundleId"})
    class BkbTableChart extends Structure {
        public BkbStr id; public BkbStr desc; public Pointer tags; public SizeT tagsLen; public BkbStr bundleId;
        public BkbTableChart() {}
        public BkbTableChart(Pointer pointer) { super(pointer); read(); }
    }

    @Structure.FieldOrder({"level", "tags", "tagsLen", "charts", "chartsLen"})
    class BkbTableLevel extends Structure {
        public BkbStr level; public Pointer tags; public SizeT tagsLen; public Pointer charts; public SizeT chartsLen;
        public BkbTableLevel() {}
        public BkbTableLevel(Pointer pointer) { super(pointer); read(); }
    }

    @Structure.FieldOrder({"name", "query", "tags", "tagsLen", "charts", "chartsLen"})
    class BkbTableFolder extends Structure {
        public BkbStr name; public BkbStr query; public Pointer tags; public SizeT tagsLen; public Pointer charts; public SizeT chartsLen;
        public BkbTableFolder() {}
        public BkbTableFolder(Pointer pointer) { super(pointer); read(); }
    }

    @Structure.FieldOrder({"name", "symbol", "gamemode", "updated", "tags", "tagsLen", "assets", "assetsLen", "levels", "levelsLen", "folders", "foldersLen"})
    class BkbTable extends Structure {
        public BkbStr name; public BkbStr symbol; public BkbStr gamemode; public BkbTimestamp updated;
        public Pointer tags; public SizeT tagsLen; public Pointer assets; public SizeT assetsLen;
        public Pointer levels; public SizeT levelsLen; public Pointer folders; public SizeT foldersLen;
        BkbTable() {}
        BkbTable(Pointer pointer) { super(pointer); read(); }
    }

    @Structure.FieldOrder({"url"})
    class BkbServerConfig extends Structure {
        public String url;
        BkbServerConfig(String url) { this.url = url; write(); }
    }

    @Structure.FieldOrder({"charts", "tables", "courses", "packs", "assetCount", "assetBytes", "dbBytes"})
    class BkbStats extends Structure {
        public long charts; public long tables; public long courses; public long packs;
        public long assetCount; public long assetBytes; public long dbBytes;
    }

    @Structure.FieldOrder({"kind", "value"})
    class BkbDataId extends Structure {
        public int kind; public String value;
        BkbDataId(int kind, String value) { this.kind = kind; this.value = value; write(); }
    }

    @Structure.FieldOrder({"isSome", "value"})
    class BkbOptionalU64 extends Structure { public byte isSome; public long value; }

    @Structure.FieldOrder({"bytes", "total", "itemsDone", "itemsTotal", "state"})
    class BkbDownloadProgress extends Structure {
        public long bytes; public BkbOptionalU64 total; public long itemsDone; public BkbOptionalU64 itemsTotal; public int state;
    }

    @Structure.FieldOrder({"isSome", "value"})
    class BkbOptionalDownloadProgress extends Structure { public byte isSome; public BkbDownloadProgress value; }

    @Structure.FieldOrder({"kind", "value"})
    class BkbOwnedDataId extends Structure { public int kind; public BkbString value; }

    @Structure.FieldOrder({"key", "progress", "error"})
    class BkbDownloadSnapshot extends Structure {
        public BkbOwnedDataId key; public BkbDownloadProgress progress; public BkbString error;
        public BkbDownloadSnapshot() {}
        public BkbDownloadSnapshot(Pointer pointer) { super(pointer); read(); }
    }

    @Structure.FieldOrder({"items", "itemsLen"})
    class BkbDownloadSnapshotList extends Structure {
        public Pointer items; public SizeT itemsLen;
        ByValue byValue() { ByValue value = new ByValue(); value.items = items; value.itemsLen = itemsLen; value.write(); return value; }
        public static final class ByValue extends BkbDownloadSnapshotList implements Structure.ByValue {}
    }

    @Structure.FieldOrder({"total", "queued", "running", "failed", "done", "cancelled", "firstError"})
    class BkbDownloadOverview extends Structure {
        public long total; public long queued; public long running; public long failed; public long done; public long cancelled;
        public BkbString firstError;
        ByValue byValue() {
            ByValue value = new ByValue();
            value.total = total; value.queued = queued; value.running = running; value.failed = failed;
            value.done = done; value.cancelled = cancelled; value.firstError = firstError; value.write(); return value;
        }
        public static final class ByValue extends BkbDownloadOverview implements Structure.ByValue {}
    }

    @Structure.FieldOrder({"total", "queued", "running", "failed", "done", "cancelled", "firstError", "downloads", "downloadsLen", "hasMore"})
    class BkbDownloadListResult extends Structure {
        public long total; public long queued; public long running; public long failed; public long done; public long cancelled;
        public BkbString firstError; public Pointer downloads; public SizeT downloadsLen; public byte hasMore;
        ByValue byValue() {
            ByValue value = new ByValue();
            value.total = total; value.queued = queued; value.running = running; value.failed = failed;
            value.done = done; value.cancelled = cancelled; value.firstError = firstError;
            value.downloads = downloads; value.downloadsLen = downloadsLen; value.hasMore = hasMore;
            value.write(); return value;
        }
        public static final class ByValue extends BkbDownloadListResult implements Structure.ByValue {}
    }

    @Structure.FieldOrder({"item", "message"})
    class BkbCollectionDownloadDataFailure extends Structure {
        public BkbOwnedDataId item; public BkbString message;
        public BkbCollectionDownloadDataFailure() {}
        public BkbCollectionDownloadDataFailure(Pointer pointer) { super(pointer); read(); }
    }

    @Structure.FieldOrder({"chartsDownloaded", "chartsSkipped", "chartsFailed", "bundlesDownloaded", "bundlesSkipped", "bundlesFailed", "assetsDownloaded", "assetsSkipped", "assetsFailed", "errors", "errorsLen"})
    class BkbCollectionDownloadDataReport extends Structure {
        public long chartsDownloaded; public long chartsSkipped; public long chartsFailed;
        public long bundlesDownloaded; public long bundlesSkipped; public long bundlesFailed;
        public long assetsDownloaded; public long assetsSkipped; public long assetsFailed;
        public Pointer errors; public SizeT errorsLen;
        ByValue byValue() {
            ByValue value = new ByValue();
            value.chartsDownloaded = chartsDownloaded; value.chartsSkipped = chartsSkipped; value.chartsFailed = chartsFailed;
            value.bundlesDownloaded = bundlesDownloaded; value.bundlesSkipped = bundlesSkipped; value.bundlesFailed = bundlesFailed;
            value.assetsDownloaded = assetsDownloaded; value.assetsSkipped = assetsSkipped; value.assetsFailed = assetsFailed;
            value.errors = errors; value.errorsLen = errorsLen; value.write(); return value;
        }
        public static final class ByValue extends BkbCollectionDownloadDataReport implements Structure.ByValue {}
    }

    final class Loader {
        private Loader() {}
        static NativeBindings load() {
            String explicit = System.getProperty("backbeat.native.path");
            String library = explicit != null ? explicit : extractBundledLibrary().toString();
            NativeBindings bindings = Native.load(library, NativeBindings.class, Map.of(Library.OPTION_STRING_ENCODING, "UTF-8"));
            int version = bindings.bkb_libversion();
            if (version != LIBVERSION) throw new BackbeatException("Incompatible Backbeat native library version: expected " + LIBVERSION + ", got " + version, null);
            return bindings;
        }
        private static Path extractBundledLibrary() {
            String platform = platform();
            String filename = mappedLibraryName();
            String resource = "/ac/backbeat/sdk/natives/" + platform + "/" + filename;
            try (InputStream input = NativeBindings.class.getResourceAsStream(resource)) {
                if (input == null) throw new BackbeatException("No Backbeat native library for " + platform, null);
                Path extracted = Files.createTempFile("backbeat-c-sdk-", filename.substring(filename.lastIndexOf('.')));
                Files.copy(input, extracted, StandardCopyOption.REPLACE_EXISTING);
                extracted.toFile().deleteOnExit();
                return extracted;
            } catch (IOException error) {
                throw new BackbeatException("Failed to extract the Backbeat native library", error);
            }
        }
        private static String platform() {
            String os = System.getProperty("os.name").toLowerCase(Locale.ROOT);
            String architecture = System.getProperty("os.arch").toLowerCase(Locale.ROOT);
            String arch;
            if (architecture.equals("aarch64") || architecture.equals("arm64")) arch = "aarch64";
            else if (architecture.equals("x86_64") || architecture.equals("amd64")) arch = "x86-64";
            else throw new BackbeatException("Unsupported architecture: " + architecture, null);
            if (os.contains("win")) return "windows-" + arch;
            if (os.contains("mac") || os.contains("darwin")) return "macos-" + arch;
            if (os.contains("linux")) return "linux-" + arch;
            throw new BackbeatException("Unsupported platform: " + os + " / " + architecture, null);
        }
        private static String mappedLibraryName() {
            String os = System.getProperty("os.name").toLowerCase(Locale.ROOT);
            if (os.contains("win")) return "backbeat_c_sdk.dll";
            if (os.contains("mac") || os.contains("darwin")) return "libbackbeat_c_sdk.dylib";
            return "libbackbeat_c_sdk.so";
        }
    }
}
