[package]
name = "backbeat_vf_fs"
version = "0.1.0"
edition.workspace = true
authors = ["zkldi <zkldi@proton.me>"]
readme = "README.md"
license = "GPL-3.0"
repository = "https://github.com/zkldi/backbeat"

[dependencies]
backbeat_core = { workspace = true, features = ["sqlx"] }
backbeat_packager.workspace = true
backbeat_sdk = { workspace = true }
sqlx = { workspace = true }
moka = { workspace = true, features = ["sync"] }
parking_lot = { workspace = true }
libc = { workspace = true }
thiserror = { workspace = true }
futures = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
backbeat_sdk = { workspace = true, features = ["test-util"] }
backbeat_store_config.workspace = true
rg_formats.workspace = true
tempfile = { workspace = true }
tokio = { workspace = true }
